COMPANY_SECTOR_CHOISES = (
    ('', 'Please choose'),
    ('0', 'Advanced Manufacturing'),
    ('1', 'Aerospace'),
    ('2', 'Agri-Tech'),
    ('3', 'Aid Funded Business'),
    ('4', 'Airports'),
    ('5', 'Automotive'),
    ('6', 'Biotechnology and Pharmaceuticals'),
    ('7', 'Business (and Consumer) Services'),
    ('8', 'Capital Investment'),
    ('9', 'Clothing, Footwear and Fashion'),
    ('10', 'Communications'),
    ('12', 'Construction'),
    ('13', 'Creative and Media'),
    ('14', 'Defence (DSO)'),
    ('15', 'Education and Training'),
    ('16', 'Electronics and IT Hardware'),
    ('17', 'Energy'),
    ('18', 'Environment'),
    ('19', 'Financial Services (including Professional Services)'),
    ('20', 'Food and Drink'),
    ('21', 'Giftware, Jewellery and Tableware'),
    ('22', 'Global Sports'),
    ('23', 'Healthcare and Medical'),
    ('24', 'Household Goods, Furniture and Furnishings'),
    ('25', 'Infrastructure (Investment Only)'),
    ('26', 'Leisure and Tourism'),
    ('27', 'Life Sciences'),
    ('28', 'Marine'),
    ('29', 'Manufacturing'),
    ('30', 'Mass Transport'),
    ('31', 'Mining'),
    ('32', 'Nuclear'),
    ('33', 'Oil and Gas'),
    ('34', 'Ports and Logistics'),
    ('35', 'Power'),
    ('36', 'Railways'),
    ('37', 'Renewables'),
    ('38', 'Retail'),
    ('39', 'Security'),
    ('40', 'Software and Computer Services'),
    ('41', 'Space'),
    ('42', 'Technology'),
    ('43', 'Textiles, Interior Textiles and Carpets'),
    ('OTHER', 'Please specify'),
)


EMPLOYEES_NUMBER_CHOISES = (
    ('', 'Please choose'),
    ('0', 'Fewer than 10'),
    ('1', '10 to 49'),
    ('2', '50 to 250'),
    ('3', 'More than 250'),
)

HEARD_ABOUT_CHOISES = (
    ('', 'Please choose'),
    ('0', 'In the press'),
    ('1', 'International Trade Advisor'),
    ('2', 'Another Company'),
    ('3', 'Trade Association'),
    ('4', 'On great.gov.uk'),
    ('5', 'Social media'),
    ('6', 'Email from The Department for International Trade (DIT)'),
    ('7', 'At an event'),
    ('OTHER', 'Please specify'),
)
